### PR TITLE
Fix notebooks examples and mybinder environment

### PR DESCRIPTION
**Pull request by kmarchais**
This PR fixes the jupyter notebooks examples of microgen and the environment for mybinder.

Also the rasterEllipsoid example in `examples/3Doperations` and `examples/jupyter_notebooks/examples.ipynb`  is not working as expected.

For later : there might be a faster way for the building process using a container already built.

### CODE REVIEW

**Comment by chemiskyy** [comment]
Is the pyproject.toml should have such specific version for Jupyter ?

```
jupyter = [
    "jupyterlab==3.4.8",
    "jupyter-cadquery==3.5.2",
    "ipyvtklink==0.2.3",
    "ipygany==0.5.0",
    "sidecar==0.5.2",
    "jupyterview==0.5.2",
]
```

**Comment by kmarchais** [comment]
Probably this is too restrictive indeed but I remember having issues with mybinder. This was a configuration that worked. I will need to check it again.

**Comment by kmarchais** [comment]
`jupyterlab<3.6` seems to be the one that works best. With higher values it tests all the versions possible for the latest version till 3.5.3 that works. Also I don't understand why but it seems it also downloads all the other versions of jupyterlab 3.

However, the configuration of this mybinder environment takes so much time that it loses all the interest of mybinder in my opinion.

**Comment by chemiskyy** [comment]
This PR is well documented and following the discussion about the dependencies version it seems that an optimal solution has been fond for the pyproject.toml. Ready to merge

**Pull request merged**
