### PR TITLE
Fix infill and coordinates issue

### LINKED ISSUE #64: Infill feature update made cylindrical and spherical tpms to use a cartesian grid
### Describe the bug, what's wrong, and what you expected.

Since the infill feature update, a change in the `_compute_tpms_field` method made impossible to make tpms surfaces follow cylindrical or spherical coordinates.

```python
    def _compute_tpms_field(self: Tpms) -> None:
        """Compute the TPMS scalar field on the grid."""
        linspaces: list[npt.NDArray[np.float64]] = [
            np.linspace(
                -0.5 * cell_size_axis * repeat_cell_axis,
                0.5 * cell_size_axis * repeat_cell_axis,
                self.resolution * repeat_cell_axis,
            )
            for repeat_cell_axis, cell_size_axis in zip(
                self.repeat_cell,
                self.cell_size,
            )
        ]

        x, y, z = np.meshgrid(*linspaces)

        self.grid = self._create_grid(x, y, z)

        k_x, k_y, k_z = 2.0 * np.pi / self.cell_size
        x, y, z = self.grid.points.T
        tpms_field = self.surface_function(
            k_x * (x + self.phase_shift[0]),
            k_y * (y + self.phase_shift[1]),
            k_z * (z + self.phase_shift[2]),
        )

        self.grid["surface"] = tpms_field.ravel(order="F")
```

For the infill feature, the line `x, y, z = self.grid.points.T` has been introduced since x, y, z do not have the same dimensions as the grid because the grid for infill have a different shape after clipping with the surface of the object filled with TPMS.

But when we want to generate a cylindrical or spherical TPMS, now the x, y, z are the points of the grid in the new frame while they are required to be in the original cartesian frame.

I think the solution to this problem is to save these original coordinates in the grid as a field.

### PR DESCRIPTION
**Pull request by kmarchais**
Fixes #64.

Since the introduction of the infill feature, the cylindrical and spherical tpms geometries were not correctly computed and were using wrong coordinates to compute the tpms field in the grid.

To generate a cylindrical grid for example, we must transform the cartesian coordinates x, y, z to cylindrical coordinates.
When computing the TPMS field, we need to use the original x, y, z to have this rotation effect.

This animation may explain better than words.
coords

After bringing the infill feature, since the grid where is computed the tpms field has not the same shape as x, y, z after clipping with the object infilled, one option was to get x, y, z by using the grid's `points` attribute.

But this is working only in a cartesian frame. In cylindrical or spherical coordinates the coordinates of the points are not the original x, y, z of the meshgrid.

To solve this problem, one solution is to store the original coordinates as a field in the grid to use them in the computation of the tpms field. Maybe there is a better solution.

### CODE REVIEW

**Comment by ricardo0115** [comment]
To facilitate the PR review for reviewers can you describe and talk a little bit more about the bug that you are trying to fix and how you did it please ?

**Comment by kmarchais** [comment]
Thanks for the review, I added some explanation of the problem solved.

**Comment by rdesparbes** [comment]
The correction looks good to me! 
Is there a way to add a test to modify an existing one to avoid regressions for this correction?

**Comment by kmarchais** [comment]
Thanks for your comment, I just added a test that checks if the `coords` field is the same as the corresponding cartesian coordinates.
Until now, I couldn't find how to test if we have the correct tpms field computed.

**Comment by ricardo0115** [comment]
LGTM, is important to take into account that the test `test_tpms_given_coord_system_tpms_coordinates_field_must_be_in_cartesian_frame` is testing an implementation detail such as storing the grid coordinates in a dictionary. This test may broke easily later with minor modifications. We can keep it for the moment but we should think in a better way to test this in the future.

**Pull request merged**
